---
- name: Enable Elasticsearch
  systemd:
    name: elasticsearch
    enabled: true
    daemon_reload: true

- name: Restart Elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
    enabled: true
