---
- name: Start Elasticsearch
  systemd:
    name: elasticsearch
    state: started

- name: Enable Elasticsearch
  systemd:
    name: elasticsearch
    enabled: yes

- name: Restart Elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
    enabled: yes  
# handlers file for elasticsearch
