# ------------------ DEBIAN FAMILY TASKS ------------------
- name: Update apt repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Upgrade all packages on servers
  apt:
    upgrade: dist
    force_apt_get: yes
  when: ansible_os_family == "Debian"

- name: Install necessary packages on Debian
  apt:
    name:
      - nginx
      - openjdk-17-jdk
      - vim
      - wget
    state: present
  when: ansible_os_family == "Debian"

- name: Import the Elasticsearch PGP key on Debian
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    keyring: /usr/share/keyrings/elasticsearch-keyring.gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Add the Elasticsearch repository on Debian
  lineinfile:
    path: /etc/apt/sources.list.d/elastic-8.x.list
    line: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
    create: yes
  when: ansible_os_family == "Debian"

- name: Install Elasticsearch package on Debian
  apt:
    name: elasticsearch
    state: present
    update_cache: yes
  notify:
    - Start Elasticsearch
    - Enable Elasticsearch
    - Restart Elasticsearch
  when: ansible_os_family == "Debian"

- name: Configure elasticsearch.yml on Debian
  block:
    - name: Set network.host to 0.0.0.0
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#?network.host:'
        line: 'network.host: 0.0.0.0'

    - name: Set http.port to 9200
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#?http.port:'
        line: 'http.port: 9200'

    - name: Disable security for demo
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        line: '{{ item }}'
        create: yes
      loop:
        - 'xpack.security.enabled: false'
        - 'xpack.security.transport.ssl.enabled: false'
        - 'xpack.security.http.ssl.enabled: false'
  when: ansible_os_family == "Debian"

# ------------------ REDHAT FAMILY TASKS ------------------
- name: Install dependencies on RedHat
  yum:
    name:
      - java-17-openjdk
      - nginx
      - wget
      - vim
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution != "Amazon"

- name: Import the Elasticsearch GPG key on RedHat
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution != "Amazon"

- name: Add Elasticsearch repo on RedHat
  get_url:
    url: https://artifacts.elastic.co/packages/8.x/yum/elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
  when: ansible_os_family == "RedHat" and ansible_distribution != "Amazon"

- name: Install Elasticsearch on RedHat
  yum:
    name: elasticsearch
    state: present
  notify:
    - Start Elasticsearch
    - Enable Elasticsearch
    - Restart Elasticsearch
  when: ansible_os_family == "RedHat" and ansible_distribution != "Amazon"

- name: Configure elasticsearch.yml on RedHat
  block:
    - name: Set network.host to 0.0.0.0
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#?network.host:'
        line: 'network.host: 0.0.0.0'

    - name: Set http.port to 9200
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#?http.port:'
        line: 'http.port: 9200'

    - name: Disable security for demo
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        line: '{{ item }}'
        create: yes
      loop:
        - 'xpack.security.enabled: false'
        - 'xpack.security.transport.ssl.enabled: false'
        - 'xpack.security.http.ssl.enabled: false'
  when: ansible_os_family == "RedHat" and ansible_distribution != "Amazon"

# ------------------ AMAZON LINUX TASKS ------------------
- name: Install dependencies on Amazon Linux
  yum:
    name:
      - java-11-amazon-corretto
      - nginx
      - wget
      - vim
    state: present
  when: ansible_distribution == "Amazon"

- name: Import the Elasticsearch GPG key on Amazon Linux
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_distribution == "Amazon"

- name: Add Elasticsearch repo on Amazon Linux manually
  copy:
    dest: /etc/yum.repos.d/elasticsearch.repo
    content: |
      [elasticsearch]
      name=Elasticsearch repository for 8.x packages
      baseurl=https://artifacts.elastic.co/packages/8.x/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled=1
      autorefresh=1
      type=rpm-md
  when: ansible_distribution == "Amazon"

- name: Install Elasticsearch on Amazon Linux
  yum:
    name: elasticsearch
    state: present
  notify:
    - Start Elasticsearch
    - Enable Elasticsearch
    - Restart Elasticsearch
  when: ansible_distribution == "Amazon"

- name: Configure elasticsearch.yml on Amazon Linux
  block:
    - name: Set network.host to 0.0.0.0
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#?network.host:'
        line: 'network.host: 0.0.0.0'

    - name: Set http.port to 9200
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#?http.port:'
        line: 'http.port: 9200'

    - name: Disable security for demo
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        line: '{{ item }}'
        create: yes
      loop:
        - 'xpack.security.enabled: false'
        - 'xpack.security.transport.ssl.enabled: false'
        - 'xpack.security.http.ssl.enabled: false'
  when: ansible_distribution == "Amazon"

# ------------------ SUSE FAMILY TASKS ------------------
- name: Install dependencies on SUSE
  zypper:
    name:
      - java-17-openjdk
      - nginx
      - wget
      - vim
    state: present
  when: ansible_os_family == "Suse"

- name: Import Elasticsearch GPG key on SUSE
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_os_family == "Suse"

- name: Add Elasticsearch repo on SUSE
  get_url:
    url: https://artifacts.elastic.co/packages/8.x/yum/elasticsearch.repo
    dest: /etc/zypp/repos.d/elasticsearch.repo
  when: ansible_os_family == "Suse"

- name: Install Elasticsearch on SUSE
  zypper:
    name: elasticsearch
    state: present
  notify:
    - Start Elasticsearch
    - Enable Elasticsearch
    - Restart Elasticsearch
  when: ansible_os_family == "Suse"

- name: Configure elasticsearch.yml on SUSE
  block:
    - name: Set network.host to 0.0.0.0
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#?network.host:'
        line: 'network.host: 0.0.0.0'

    - name: Set http.port to 9200
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#?http.port:'
        line: 'http.port: 9200'

    - name: Disable security for demo
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        line: '{{ item }}'
        create: yes
      loop:
        - 'xpack.security.enabled: false'
        - 'xpack.security.transport.ssl.enabled: false'
        - 'xpack.security.http.ssl.enabled: false'
  when: ansible_os_family == "Suse"
